//data formats
var FORMAT_GJ_CACHED_TILES = {"name" : "FORMAT_GJ_CACHED_TILES", "binary" : false, "value" : 1};
var FORMAT_BINARY_1B_CACHED_TILES = {"name" : "FORMAT_BINARY_1B_CACHED_TILES", "binary" : true, "value" : 2};
var FORMAT_BINARY_8B_ONDEMAND = {"name" : "FORMAT_BINARY_8B_ONDEMAND", "binary" : true, "value" : 3};
var FORMAT_BINARY_2B_ONDEMAND = {"name" : "FORMAT_BINARY_2B_ONDEMAND", "binary" : true, "value" : 4};
var FORMAT_BINARY_1B_TILES_ONDEMAND = {"name" : "FORMAT_BINARY_1B_TILES_ONDEMAND", "binary" : true, "value" : 5};
var FORMAT_GJ_CACHED_TILES_SIMPLE = {"name" : "FORMAT_GJ_CACHED_TILES_SIMPLE", "binary" : false, "value" : 6};
var FORMAT_BINARY_1B_CACHED_TILES_SIMPLE = {"name" : "FORMAT_BINARY_1B_CACHED_TILES_SIMPLE", "binary" : true, "value" : 7};
var FORMAT_BINARY_8B_ONDEMAND_SIMPLE = {"name" : "FORMAT_BINARY_8B_ONDEMAND_SIMPLE", "binary" : true, "value" : 8};
var FORMAT_BINARY_2B_ONDEMAND_SIMPLE = {"name" : "FORMAT_BINARY_2B_ONDEMAND_SIMPLE", "binary" : true, "value" : 9};

var DataFormatType =
{
    "FORMAT_GJ_CACHED_TILES" : FORMAT_GJ_CACHED_TILES,
    "FORMAT_BINARY_1B_CACHED_TILES" : FORMAT_BINARY_1B_CACHED_TILES,
    "FORMAT_BINARY_8B_ONDEMAND" : FORMAT_BINARY_8B_ONDEMAND,
    "FORMAT_BINARY_2B_ONDEMAND" : FORMAT_BINARY_2B_ONDEMAND,
    "FORMAT_BINARY_1B_TILES_ONDEMAND" : FORMAT_BINARY_1B_TILES_ONDEMAND,
    "FORMAT_GJ_CACHED_TILES_SIMPLE" : FORMAT_GJ_CACHED_TILES_SIMPLE,
    "FORMAT_BINARY_1B_CACHED_TILES_SIMPLE" : FORMAT_BINARY_1B_CACHED_TILES_SIMPLE,
    "FORMAT_BINARY_8B_ONDEMAND_SIMPLE" : FORMAT_BINARY_8B_ONDEMAND_SIMPLE,
    "FORMAT_BINARY_2B_ONDEMAND_SIMPLE" : FORMAT_BINARY_2B_ONDEMAND_SIMPLE,
};
